#!/usr/bin/env bash
# snmpeek installer: creates a venv, installs dependencies, sets up
# config.yaml, and installs a short `peek` launcher command.
set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$REPO_DIR/venv"
BIN_DIR="$HOME/.local/bin"

echo "==> snmpeek installer"
echo "    repo: $REPO_DIR"
echo ""

if [ ! -d "$VENV_DIR" ]; then
    echo "==> Creating virtual environment..."
    python -m venv "$VENV_DIR"
else
    echo "==> Virtual environment already exists, reusing it."
fi

echo "==> Installing dependencies (this can take a minute)..."
"$VENV_DIR/bin/pip" install --upgrade pip --quiet
"$VENV_DIR/bin/pip" install -r "$REPO_DIR/requirements.txt"

if [ ! -f "$REPO_DIR/config.yaml" ]; then
    echo "==> Creating config.yaml from config.example.yaml..."
    cp "$REPO_DIR/config.example.yaml" "$REPO_DIR/config.yaml"
    echo "    Edit $REPO_DIR/config.yaml to set your subnet before first run."
else
    echo "==> config.yaml already exists, leaving it untouched."
fi

echo "==> Installing 'peek' launcher to $BIN_DIR..."
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/peek" << LAUNCHER
#!/usr/bin/env bash
# Auto-generated by snmpeek's install.sh - launches snmpeek from anywhere.
exec sudo "$VENV_DIR/bin/python" "$REPO_DIR/cli.py" "\$@"
LAUNCHER
chmod +x "$BIN_DIR/peek"

echo ""
echo "==> Done."

case ":$PATH:" in
    *":$BIN_DIR:"*)
        echo "You're all set - just run:  peek"
        ;;
    *)
        echo "NOTE: $BIN_DIR isn't on your PATH yet. Add it, then restart your shell:"
        echo ""
        echo "  bash/zsh:  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc   # or ~/.zshrc"
        echo "  fish:      fish_add_path \$HOME/.local/bin"
        echo ""
        echo "Then run:  peek"
        ;;
esac
